### ISSUE TITLE
Feature request for first and last CSS classes

### ISSUE THREAD

**Issue by lessoffensive** [themephe/recent-posts-widget-extended#22]
Thanks for the great WP extension!  My apologies if I'm not filing this properly, but I've been working with your plugin for a project recently and it's worked fantastically, but I needed a single one-line modification to make it have first and last CSS classes on the list of posts (since I wanted separators between each post, but not on the beginning or end of them).  Would you all be willing to consider implementing this into your extension?  Here's the change:

in: recent-posts-widget-extended/includes/widget-recent-posts-extended.php
line 127, replace current content:

<li class="rpwe-clearfix">

with:

<li class="rpwe-clearfix <?php if ($post === reset($rpwewidget)) echo 'first'; elseif ($post === end($rpwewidget)) echo 'last'; ?>">

which will add a "first" and "last" CSS class to the first and last posts, respectively.

Thanks again for the great extension and for your consideration with regards to this change!

**Comment by satrya** [comment]
https://github.com/themephe/recent-posts-widget-extended/commit/de0e8fe52dbdfbd31f633d9d305738641e9a36cb
